apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    sidecar.istio.io/inject: "true"
  name: istio-test-callee
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: istio-test-callee
  serviceName: istio-test-callee
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: istio-test-callee
    spec:
      restartPolicy: Always
      containers:
      - image: chaeyk/istio-test-callee:0.0.1
        imagePullPolicy: IfNotPresent
        name: istio-test-callee
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 3
          timeoutSeconds: 10

